### ISSUE TITLE
x in datetime.datetime.strptime(x,'%Y-%m-%dT%H:%M:%SZ')

### ISSUE THREAD

**Issue by st4141** [pangyuteng/make-og-pixel-great-again#1]
Is x defined and correctly used in fetchall.py ?
`df.creationTime = datetime.datetime.strptime(x,'%Y-%m-%dT%H:%M:%SZ')`

**Comment by pangyuteng** [comment]
wow. good catch. how did that line even get in there!?! looks like a bug to me...!!! 

https://github.com/pangyuteng/make-og-pixel-great-again/blob/main/fetchall.py#L63

above line removed in branch main @st4141  thanks!
