### ISSUE TITLE
crawlall.py secret errors

### ISSUE THREAD

**Issue by AmmarIjaz** [pangyuteng/make-og-pixel-great-again#2]
Getting two errors:

`(gphotos-env-01) PS D:\> .\gphotos-env-01\Scripts\python.exe .\crawlall.py
Traceback (most recent call last):
  File "D:\..\crawlall.py", line 8, in <module>
    with open("secret.json",'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'secret.json'`

Renaming the client_secret.json file I used for fetchall.py to secret.json gave this error:

`(gphotos-env-01) PS D:\> .\gphotos-env-01\Scripts\python.exe .\crawlall.py
Traceback (most recent call last):
  File "D:\..\crawlall.py", line 10, in <module>
    email,password,backup_email = secret["email"],secret["password"],secret["backupemail"]
                                  ~~~~~~^^^^^^^^^
KeyError: 'email'`

Not sure what I'm doing incorrectly here. Thoughts?

Thanks for all your hard work!

**Comment by pangyuteng** [comment]
Hello. Thank you for visiting.
I have updated the readme.

You have to create a "secret.json" file containing your gmail credentials.

sample json file content
```
{
  "email":"asdf@ok.com",
  "password":"verysecret",
  "backupemail":"bak@aol.com"
}
```
